### ISSUE TITLE
Research how to have a trustless token brigde

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/telos-token-bridge#1]
### Goal
Identify if it is possible and how to have a **trustless** token bridge, just like oracle brigde.

#### Acceptance criteria
- [ ] #12
- [x] @tomtomcrypto agrees its trustless
- [x] Create the issues for developing the bridge
- [ ] #13

**Comment by tomtomcrypto** [comment]
WIP issue list:

- [ ] Feature: Token registration on Antelope (for access to mint)
- [ ] Feature: Token registration on EVM (for access to mint)
- [ ] Feature: Bridge tokens from Antelope to EVM
- [ ] Feature: Bridge tokens from EVM to Antelope
- [ ] Bridge listeners (Oracle Scripts)
- [ ] Bridge monitoring (Telos Monitor)
