### ISSUE TITLE
Core: Write Antelope escrow.brdg contract

### ISSUE THREAD

**Issue by tomtomcrypto** [telosnetwork/telos-token-bridge#11]
## Description

Contract to lock eosio.token for the bridge. Only bridge and BPs (???) can get money out.

_Still unsure about this, might as well just lock those inside the bridge, altho escrow would likely never need to get updated_

**Comment by karynemayer** [comment]
@poplexity what is the priority of this one?

**Comment by karynemayer** [comment]
We don't need to track down who put the tokens there
