### ISSUE TITLE
Unit tests on Antelope

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/telos-token-bridge#16]
## Overview

The goal is to find out how to properly write tests using Antelope.

## Acceptance criteria

- Efficient way to write them
- Successfully run tests

## Time Box

12 hours

#### Suggestion
https://docs.liquidapps.io/liquidapps-documentation/working-with-zeus-sdk/overview

https://www.genereos.io/qtest-smart-contract-testing-library/

**Comment by tomtomcrypto** [comment]
I am using guillermo's suggestion of QTest (https://github.com/GenerEOS/Qtest)
